# Generated by Django 4.0.6 on 2022-07-14 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iamdt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
            ],
            options={
                "verbose_name": "진료단계별 담당자",
                "verbose_name_plural": "진료단계별 담당자",
            },
        ),
        migrations.AddField(
            model_name="medicaldetail",
            name="staff",
            field=models.ManyToManyField(
                limit_choices_to={"is_active": True, "is_staff": True},
                related_name="schedule",
                through="iamdt.MedicalStaff",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당자",
            ),
        ),
        migrations.AddField(
            model_name="medicalstaff",
            name="detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="iamdt.medicaldetail",
                verbose_name="진료단계",
            ),
        ),
        migrations.AddField(
            model_name="medicalstaff",
            name="staff",
            field=models.ForeignKey(
                limit_choices_to={"is_active": True, "is_staff": True},
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당자",
            ),
        ),
    ]
