# Generated by Django 4.0.6 on 2022-07-13 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iamdt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0~32767",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="나이",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "companion",
                    models.ForeignKey(
                        help_text="병원 입장에서는 고객이지만 환자 입장에서는 동행인입니다.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="iamdt.customer",
                        verbose_name="동행인",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자 리스트",
            },
        ),
    ]
