# Generated by Django 4.0.6 on 2022-07-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iamdt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("register", "접수"),
                            ("examination", "진료"),
                            ("diagnosys", "진단"),
                            ("treatment", "처치"),
                            ("counseling", "결과 설명/상담"),
                            ("payment", "수납"),
                            ("discharge", "퇴원"),
                        ],
                        default="register",
                        max_length=15,
                        verbose_name="현재단계",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registers",
                        to="iamdt.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "진료 접수",
                "verbose_name_plural": "진료 접수 리스트",
            },
        ),
    ]
