# Generated by Django 4.0.6 on 2022-07-14 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iamdt", "0002_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("register", "접수"),
                            ("examination", "진료"),
                            ("diagnosys", "진단"),
                            ("treatment", "처치"),
                            ("counseling", "결과 설명/상담"),
                            ("payment", "수납"),
                            ("discharge", "퇴원"),
                        ],
                        default="register",
                        max_length=15,
                        verbose_name="단계",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("wait", "대기"), ("complete", "완료")],
                        default="wait",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "creator",
                    models.ForeignKey(
                        limit_choices_to={"is_active": True, "is_staff": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="details",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "register",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="details",
                        to="iamdt.register",
                        verbose_name="진료접수",
                    ),
                ),
            ],
            options={
                "verbose_name": "진료 내역",
                "verbose_name_plural": "진료 내역",
            },
        ),
    ]
